### ISSUE TITLE
一些关于标定图片选取的问题

### ISSUE THREAD

**Issue by Ma-Weijian** [1368069096/Calibration_ZhangZhengyou_Method#1]
就是我用dalao你的代码跑了一下我自己手机拍的图片，可结果误差在0.7左右，不太理想。
我输入的照片是拿一部旧手机（红米5A）的单摄像头拍摄的，分辨率是3120*4160，一共26张。
dalao我看到你用的输入图片貌似是640*480的，想问一下dalao'在拍摄的时候使用的是什么设备，有没有经过什么预处理，还有就是在调用opencv的库的时候有没有一些特别要调的参数（我好像没看出来）。另外就是如果我自己拿着那台手机标定的话，拍照的时候有没有什么技巧可以减小误差。
dalao有空的时候可以麻烦帮忙看一下，感激不尽。

**Comment by qzhou711** [comment]
我觉得你的手机摄像头在标定的时候会变焦，所以误差才这么大，最好用个定焦的镜头
