### ISSUE TITLE
矫正过的图片显示不完整

### ISSUE THREAD

**Issue by plz583585760** [1368069096/Calibration_ZhangZhengyou_Method#2]
您好，我想问一下为什么我标定过后得到的矫正图像只显示了图像的一个角落，不全，该如何解决，谢谢。

**Comment by zhiyuanyou** [comment]
用的是我的图片嘛？

**Comment by plz583585760** [comment]
https://github.com/1368069096/Calibration_ZhangZhengyou_Method/blob/c613119ffb99ce686fecbf00b10e79b9f9d8128e/calib_IR.py#L68
好像是这里自由比例的问题，我用的自己手机拍的图片，矫正效果不太好，可能是因为焦距不固定。

**Comment by zhiyuanyou** [comment]
找到问题就ok~
