### ISSUE TITLE
Wrong Output

### ISSUE THREAD

**Issue by Benson722** [1368069096/Calibration_ZhangZhengyou_Method#6]
![wrong](https://github.com/zhiyuanyou/Calibration-ZhangZhengyou-Method/assets/55974171/d78a5dfb-e635-40f3-9cb9-310356ae670c)
Amazing Output. Why it becomes a circle? :(

**Comment by zhiyuanyou** [comment]
Hi~

The code will re-organize the calibration board to a rectangle. 

For fish-eye camera, where the distortion is very large, maybe it is not suitable.

**Comment by Benson722** [comment]
Thank you for your reply. I guess the problem is too many resemble pics which leads to something wrong. The problem has been solved. :)
